### PR TITLE
Create ISPL folder and submit a solution

### PR DESCRIPTION
**Pull request by bestagini**
This is my first pull request for entering seg-2016-ml-contest. Please, do not hesitate to contact me for any issue, as I am not very practical with GitHub. I apologize for any inconvenience.

### CODE REVIEW

**Comment by kwinkunks** [comment]
Hello Paolo... thank you for the submission! Great to see another person getting involved.

Your model scored **0.565**, which is an excellent effort — it's the best anyone has done on their first attempt. So: well done! I hope you find some time to refine your model. Good luck.

**Comment by bestagini** [comment]
Hi Matt, thank you for updating everything so rapidly. I really enjoyed the idea of this challenge, and I will surely try refining the model again!

**Comment by kwinkunks** [comment]
Hello again,... It turns out that when I run your notebook, I get a higher score — **0.581**. So I've changed your score to that. I tried changing the random seed to some other values, but this is the highesst I got. Not sure why it's different from yours, with the seed. Maybe it's the version number of one or more pieces. Anyway, this puts you second overall — nice job!

**Comment by bestagini** [comment]
Thank you very much for letting me know and updating the result. Maybe I uploaded an old CSV file not generated with the latest version of the code. Anyway, I'll try re-running everything to see if I can reproduce my old result. I'll keep you updated if I find out anything.

**Comment by bestagini** [comment]
I tried running my code again on my laptop, and I obtained the same results I submitted. I'll try again on another machine (different OS, versions, etc.). Anyway, I'll make sure to explicitly write numpy, skleran, etc., versions on my next notebook.

**Comment by kwinkunks** [comment]
OK Paolo, but don't worry too much -- it's the result that I get that's important. I added my result to your repo, so you can at least see the data.

**Pull request merged**
