### PR TITLE
Solution from team HouMath

### PR DESCRIPTION
**Pull request by dalide**
Hi, our team name is HouMath, because we are from Houston and our major is mathematics.  

please check the code in the folder HouMath, we use XGBoost method.

Thanks

### CODE REVIEW

**Comment by kwinkunks** [comment]
Hello! Thank you for the submission - it's exciting to see a new team. And another team using XGBoost, which is one of our favourite tools at Agile. I will see if I can run through it now, but I'm away from the office today and so validation might take a while. (For next time, you can speed up my process a bit by providing a CSV with your prediction, based on the file `validation_data_nofacies.csv` --- but I need to be able to run your notebook anyway.)

**Comment by kwinkunks** [comment]
BTW I moved the file in `HoustonMath_team` to `HouMath` so you might want to do a pull to get synced.

**Comment by kwinkunks** [comment]
Hey guys... OK, everything went smoothly and I was able to run your notebook. Thank you for the clean code! When I run it, the prediction I get scores 0.540, which is decent for a first showing. You might want to check in your own `Prediction1.csv` so we can be sure that I am getting the prediction that you are getting.

**Comment by dalide** [comment]
Thanks a lot Matt. This is an interesting topic. We will improve our
prediction and resubmit again.

By the way, it is my first time to pull request in real activities, I am
glad that it worked.

**Pull request merged**
