### PR TITLE
added houmath edit

### PR DESCRIPTION
**Pull request by LukasMosser**
This is an edit of the excellent houmath notebook, adding in median filtered properties.
CV gives slight improvement so we shall see.

### CODE REVIEW

**Comment by kwinkunks** [comment]
Oh, sorry, I went and merged this before realizing that your `jovyan` directory is in there too... the one time I don't check the files changed... Anyway, if that's a problem for you, maybe you can figure out how to purge them?

**Comment by kwinkunks** [comment]
OK, thanks for this guys. The `Prediction_houmath_edit.csv` scores **0.599**. This is not the stochastic version though... I will not get to that until the morning. Or if you want to implement --- just make a list of 100 `y_pred` vectors and dump it out to a NumPy file.

**Comment by LukasMosser** [comment]
I dont even know what a jovyan is ^_^ Is this still an issue?

**Comment by kwinkunks** [comment]
IDK, I just deleted it from my repo... I think it's something to do with Jupyter... or maybe [this](https://github.com/jovyan)?

**Comment by LukasMosser** [comment]
Possibly,  I wasn't aware that it is even in there. Thanks for dealing with it. I'll double check my git add next time.

**Pull request merged**
