### PR TITLE
First submission

### PR DESCRIPTION
**Pull request by ShiangYong**
Algorithm : Convolutional Neural Network.
Imputed PE using regression

### CODE REVIEW

**Comment by kwinkunks** [comment]
Hello! Thank you for this... however I can't merge this pull very easily. Do you think you can make a new `git pull` from the master branch — so that the only files in the pull request are your new files? That way I know there are no conflicts. [Edit: also, please make sure your files are in a new folder called `ShiangYong` or something like that. Have a look at how other people have added their notebooks/CSV files.]

Sorry for the trouble, Shiang... In the meantime, I will try to find your results CSV and can at least give you a score.

**Comment by ShiangYong** [comment]
Hi Matt,

Hmm I think I did something wrong when I cloned and I downloaded all the
files from your repo. Sorry for the mistake! This is my first time doing
this so please bear with me.

I'm not exactly sure how to do a git pull, not sure what that means
actually. Here's what I did: I went to my repo (
https://github.com/ShiangYong/2016-ml-contest) and clicked on "New pull
request". From the number of files changed, it looks like it remembers that
I deleted all the files (other contestants' submissions) and that might be
the cause.

Could you explain how I can fix this?

Shiang Yong

**Comment by LukasMosser** [comment]
I"m looking forward to this 👍

**Comment by kwinkunks** [comment]
@ShiangYong Yes, the idea is that the only changed files are yours. You don't need to delete everything else. I'm not exactly a git expert, so this might be overkill, but maybe the easiest thing to do is as follows...

**Step 1** add the SEG repo as an 'upstream' remote for your fork: https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Step 2, IMPORTANT** — we are going to nuke everything you've done in your repo. So copy it somewhere safe first: copy **only your** files to a folder called `ShiangYong` somewhere safe, like your home directory.

**Step 3.** Now we are going to completely reset your local...

- In your fork of the repo, do `git fetch upstream`
- Now do `git reset --hard upstream/master`
- Now `mkdir ShiangYong` (or whatever name you like)
- Copy **only your** files from the 'safe' directory to this new `ShiangYong` directory
- `git add ShiangYong`
- `git commit -am "new attempt"`
- `git push origin master` (pushes to your fork)
- Make the PR as before

I'm sort of assuming you're on Linux or Mac here... I'm not clear on how you would do this on Windows, but maybe you know.

**Comment by kwinkunks** [comment]
BTW, I found what I think must be your prediction CSV file... it scores **0.545**, which is not baad at all. Nice work!

**Comment by ShiangYong** [comment]
Thanks for the detailed instructions and the score. Will redo the pull request.

**Pull request closed without merging**
