### PR TITLE
F1=56 any comments welcome

### PR DESCRIPTION
**Pull request by CannedGeo**
This is really just a copy of @kwinkunks and @brendonhall 's notebook (which is what I thought we were supposed to do) with some of my changes. I didn't stray very far from the original notebook (not a coder), but just tested different svm's and changed the test size, etc. The significant change is the svm to Linear.SVC. I did notice the F1 may vary 55-56 due to random number generation process for the Linear.SVC model. I also changed the colors to match the paper to make easier visual comparison, but maybe this isn't necessary. 

So there are some problems with this as you will probably see. Perhaps one is the test data achieves a lower F1=49. Does this make it a good model? I'm not sure. But with the goal (for now?) being to achieve best F1 for SHANKLE, this is where I am. Any thoughts?

Moving forward, I would like to look closer at log quality. It seems like some logs are noisy or have intervals where maybe they pulled tight or hole caved (Cross H @2780)? Could a flag be generated over intervals?  e.g. if the DeltaPhi is super noisy, is that helping or hurting our model? Could we exclude these data? Just some thoughts.

I worked through this the last couple weeks, let me know what you think.

Thanks!

### CODE REVIEW

**Comment by kwinkunks** [comment]
@CannedGeo Bryan, this is awesome. Thank you, and congratulations on being the first submission. I also love the example you're setting with open discussion. And 'not a coder' &mdash; kudos to you!

If you don't mind, I'd like to ask you to help us set a further precedent. Please can you create a folder in your local repo, and name it whatever you like, `CannedGeo` maybe, and put your notebook in there? I know I wasn't all that clear on this, so I'm taking a bit of a liberty asking you, I'm sorry :)

It's also better for you to do it, because if I do it, you will have to merge my version back into yours and, well, weird things can happen to notebooks in that scenario.

So, no material change required, just make a directory for your stuff (which of course you may add to later) and make a new PR. Please let me know if I need to explain more or you need a hand.

Cheers!

**Comment by CannedGeo** [comment]
Thanks for the comments @kwinkunks. And thanks for helping me through the process. I setup my local repo and have only the revised notebook in it. I think that's what I need to do, right? I will send a new PR. If it turns out incorrect, please let me know.

**Comment by LukasMosser** [comment]
@CannedGeo 
I like your ideas with filtering data. You could definitely set up a flag to filter the data, just as missing data was filtered from the dataset where PE values were missing.
Your approach would then go into what's called _feature engineering_ and can lead to very high classification precision, but requires good domain knowledge.

**Comment by CannedGeo** [comment]
Thanks @LukasMosser for the comments. It would be interesting to see how a filter/flag like this would work.

**Pull request merged**
