### PR TITLE
Create HoustonJ_sub2.csv

### PR DESCRIPTION
**Pull request by HoustonJ2013**
submitted the prediction result.

### CODE REVIEW

**Comment by kwinkunks** [comment]
Hello! Thanks for this. I laughed the the 'brutal grid search' comment. XGBoost is worth it in the end though: this was pretty dang good and scores **0.584**. Cheers!

**Comment by kwinkunks** [comment]
Oh, btw, I haven't taken the time yet to look at this in detail, but you might want to double-check that your final model is trained with all the training data. My quick glance made me think you might just have the last model from that 'brutal' loop --- and it only has a subset for cross-validation. The model might (should) improve if you retrain it before making the prediction. Does that make sense? (I hope I'm not misreading your code).

**Comment by kwinkunks** [comment]
Hello again. I got a chance to try this:

    y_pred = clf.fit(X, y).predict(X_test)
    np.save('y_pred.npy', y_pred)

This vector scores **0.600** with your hyperparameters, so I'll use that as your high score.

If you're still in the top 10 on Wednesday, I'll also be scoring all these stochastic models with the media score from 100 realizations, using different random seeds. See issue #114

**Comment by HoustonJ2013** [comment]
I just got back after a whole day of house moving.

Thanks for your comments and scores. I said "brute grid search" because I
didn't understand the XGBOOST very well, brute force is necessary to get a
quick good results. Sorry for my PC.

I heard about this competition last week from a friend, and only have 20 ~
25 hours commitment for this project. Hope there are more interesting
things coming later. For example, I found some other attempts to use
machine learning for AVO analysis from UBC (Ben Bougher, SEG 2016), but he
didn't share his code fully online.

After 4 years of working in oil industry, I felt the new trend of machine
learning and artificial intelligence is going to change how people work in
this industry, and I hope to be part of this trend.




2017-01-29 15:59 GMT-06:00 Matt Hall <notifications@github.com>:

**Comment by kwinkunks** [comment]
Gresat story, thanks for sharing. The next few years will be very exciting! I'm so glad you were able to get involved in this contest.

You might like to know about the Slack group 'Software Underground' -- a chat group for about 250 geoscience/code folks all over the world. Please join if you like at http://swung.rocks/. Lots of machine learning chat, lots of Pythonistas. Including another chap (Gram Ganssle) who's interested in reproducing Ben Bougher's work.

Cheers! Matt

**Pull request merged**
