### PR TITLE
Third Submission

### PR DESCRIPTION
**Pull request by ShiangYong**

### CODE REVIEW

**Comment by LukasMosser** [comment]
Looks really good! I like what you are doing with CNN! I've found them to overfit, but maybe your approach generalizes better! 👍

**Comment by ShiangYong** [comment]
Hi Lukas, I agree it's very easy to overfit with CNNs. This most recent submission is really doing that cause I'm out of ideas to improve my score :-) . Truthfully I'm not confident it will beat the 0.570 I had from my second submission

**Comment by kwinkunks** [comment]
Hi Siang... thank you for this. I'm afraid it only manages **0.494**. It's a really hard problem! Good luck.

**Comment by ShiangYong** [comment]
No worries, will keep plugging.

**Pull request merged**
