### PR TITLE
The Meta Submission

### PR DESCRIPTION
**Pull request by LukasMosser**

### CODE REVIEW

**Comment by kwinkunks** [comment]
Hey guys... nice effort. This scores **0.609**. You should note that it's highly likely that the CSVs in the repo are not the ones that scored the given F1s in the leaderboard, because I usually change the random seeds. Check the PR chat for each PR to see what seed gave those results. Also bear in mind #114, which isn't really resolved.

**Comment by kwinkunks** [comment]
Oh, BTW... I feel like a legit submission should really take the training data as input, and provide the prediction as output, or at least a way for me to generate it... I _suppose_ your entry sort of does this, because all those models are in the repo, but some people might call it a stretch :) In practice, it really is a stretch, because so far I haven't been able to get [edit: the Bird Team] notebook to work. This may or may not end up being an issue, but I'm still working on it.

**Comment by LukasMosser** [comment]
Well, in a way this isn't a truly serious submission, because essentially we are basing our work on the work of others, so full credit goes to the top 4 in this case. We did want to show that it is possible to achieve high(er) scores by weighting by f1-scores. We actually expected to outperform the leading submission in this case.

**Comment by ar4** [comment]
@kwinkunks Oh dear, a problem running my notebook? Is there anything I can do to assist? Would it help if I upgraded to iPython 3 (I'm still running 2)?

**Comment by kwinkunks** [comment]
@ar4 Sorry Alan! My mistake — it's the `Bird_Team` notebook I was having trouble with. They're working on a solution.

**Pull request merged**
