### PR TITLE
My first SVM submission

### PR DESCRIPTION
**Pull request by thanish**
You can find the code in the SVM_notebook_1.Rmd and the csv file of the predicted facies is SVM_predicted_facies_1.csv

### CODE REVIEW

**Comment by kwinkunks** [comment]
@thanish Thank you for providing a CSV — I can easily score that. I do need to be able to run your code too. I can try to run the commands you have provided, but it looks like you would benefit from trying [Jupyter Notebook](https://www.youtube.com/watch?v=Rc4JQWowG5I), rather than writing Markdown. Jupyter Notebooks are awesome because they have a live Python runtime in the background, so you can run the code in them.

The best way to try Jupyter Notebooks is to install Anaconda, if you haven't already, then just type `jupyter notebook` on the command line. Or, if you don't want Anaconda, try `pip install jupyter` and then run the notebook command.

**Comment by thanish** [comment]
Hi @kwinkunks. I think Jupyter notebooks are for python. I have coded in R. I'm more comfortable with R than python. I initially though of only uploading the code but then when I read it could be easy for you to run on notebook I was googling for R notebook. It gave me results that R studio latest version had R notebook which is what I have used. I never knew it was a markdown. May be for my next submission I will try to find a right notebook else don't be surprised if I upload only R code :)

**Comment by kwinkunks** [comment]
@thanish Hi... so sorry, yes, just looking at the notebooks now and I see they are in R. So I need to learn about R notebooks and RStudio. I'll let you know if I run into any snags.

You still might want to look at Jupyter — check out [the IRkernel project](https://github.com/IRkernel/IRkernel). Jupyter itself does depend on Python though, so I understand if you don't want to go there. I have no idea if/how RStudio plays with Jupyter Notebooks though.

**Comment by kwinkunks** [comment]
@thanish I found [this `ipyrmd` utility](https://github.com/chronitis/ipyrmd) and it worked (almost) perfectly to convert your `Rmd` files to `ipynb` files so I can use them with the IRKernel in Jupyter Notebook. So far so good! I will put the `ipynb` files back into the `2016-ml-contest` repo for you or others who might want them.

**Comment by thanish** [comment]
Sure if it's easy for you that should be good. So I think I can proceed with the rmd file for my future submissions though I prefer a Raw R code to be uploaded to my repo. But that's okay whichever helps you. I'm waiting to see how much my model scores as I did not do any super work with my first submission. I just wanted to kick start, get used to the process and how my initial model scores. May be from my next submission I will dig deep :)

**Comment by kwinkunks** [comment]
Scores are up! Your model got a pretty decent score. I'm impressed, given how little code you needed for this 'vanilla' model. Nice work!

I actually got a slightly better score from your code than I got from your saved CSV file, so I used my prediction from your code. This is probably due to random number generation, I'm guessing.

**Comment by thanish** [comment]
Yup the difference may be because of randomness. About the code size that is one of the beauty in using R. When I see my friends huge of chunk of code in python can be done with few lines in R. Also one of the reason I stay away from python and stick to R haha !!! even I did not expect just a vanilla model which was almost a replica of Brendon's approach with SVM could score 0.547 in the leader board. Hmmm... I can't wait to dig a little more and make the next submission :)

**Pull request merged**
