### PR TITLE
StoDIG submission

### PR DESCRIPTION
**Pull request by da-wad**
Submission from Statoil Deep-learning Interest Group.

### CODE REVIEW

**Comment by kwinkunks** [comment]
Hello! Thanks so much for participating, and welcome to the contest.

Exciting to see another deep learning attempt — I know several of the teams are interested in ConvNets in particular, and yours seems especially well thought-out. It scored **0.500** on this go, so I hope you get time to explore some tweaks to the model.

I like what you say about 'saving it the trouble of learning derivatives' but I wonder if it's worth trying a model with _less_ feature engineering? I'm happy to score more than one in a submission, if you want to feel out the solution space a bit.

So far I've been a bit surprised at deep learning being left behind a bit by random forests, but I wonder if there's enough data for them to really shine? An open question I guess.

Anyway, thanks again and best of luck!

**Comment by grajohnt** [comment]
Thanks for the comments and the quick scoring run.  We have explored quite a bit of territory here, including deeper nets, hyperparameter tuning, LSTM, etc.  I think the problem is underconstrained for DL to really shine, and this tends to show up as a lot of noise in the results.  Time permitting, we will submit some additional results, but the main learning for us was through participation and discussion of techniques and network design.  It would have been great to submit earlier and see others take the work further, and I hope that our entry prompts further discussion around the topic!

**Comment by grajohnt** [comment]
Thanks again for conducting the contest!

**Comment by kwinkunks** [comment]
Hey @grajohnt — no worries, thanks for the appreciation. It's good to hear that the contest has a small part in bringing some people together to geek out on a fun problem — definitely what it's all about. Cheers!

**Pull request merged**
