### PR TITLE
adds "well_partitioned"

### PR DESCRIPTION
**Pull request by adatum**
Same models as before but now training and validation data are partitioned based on wells instead of random sampling. It is quite possible that the data are not independent and that sampling from all wells leads to information leakage.

### CODE REVIEW

**Comment by kwinkunks** [comment]
Hello... Good thinking. Here's how those did:

0.526 - layer
**0.552** - majority
0.516 - singlemodel
0.495 - stack

Cheers,
Matt

**Comment by adatum** [comment]
It's interesting that this time, the results were very close to the performance on the validation set, unlike on previous submissions. 

Thanks for organizing this contest, Matt!

It's been a great learning experience on a deceptively easy-looking and clean data set. Not to mention a fascinating introduction to someone with no background in geophysics!

**Comment by adatum** [comment]
Minor issue: my score for the majority vote model was not updated on the leaderboard. Or is it only the top entries that were updated?

Also, is there a sequel contest planned?

**Comment by kwinkunks** [comment]
Oops, good catch, thank you. Fixed.

Sequel: not yet, but there will be more. Suggestions welcome!

**Pull request merged**
